### ISSUE TITLE
After selecting an app, a spinning progress icon is shown indefinetly

### ISSUE THREAD

**Issue by mountaindude** [j-backlin/template-on-the-fly#2]
After selecting an app in the extension, the app's icon is shown - all good.
But the properties pane never updates with the chosen app's name in the drop-down combo box, there is just a spinning icon shown there. 
Not sure if it is a problem or not - might be just a visual issue, and not a functional one. 
One other hand, I am seeing some totally empty, published apps refusing to duplicate via the extension, even though permissions are set to allow anyone, even anonymous users, full access to the source app..

![bq_lab_-_my_new_sheet___sheets_-_qlik_sense_and_qlik_sense](https://cloud.githubusercontent.com/assets/1029262/19207321/12abe060-8cf0-11e6-8e20-296859a0dcb4.png)

**Comment by j-backlin** [comment]
The spinning icon is due to that the extension uses the mashup API to get information about the template app when the extension is loaded. The side panel also uses the mashup API to get a list of all apps so that one can choose from existing apps. If the first mashup call has not finished when the panel is opened then you will see this. It should not have any effect if you have already choosen an app to use as a template. It is a timing issue, if you wait a couple of seconds more before bringing up the side panel you should not see this.
As for the app not being correctly duplicated, this is worse. I have not seen this myself. If the same user, in the hub, right-click the same app and choose Duplicate, does this give the same result or does that work better?

**Comment by mountaindude** [comment]
Hey, sorry for slow response. 
The spinning icon isn't much of an issue then - let's close this ticket and create new ones if needed for the (possible) duplication issue.
